--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Seekherr/CosmetIcsPlus
build-by-default: true
branches:
- main
projects:
  CosmetIcsPlus:
    path: ""
    libs:
      - src: xenialdan/skinapi
        version: ^0.3.0
        branch: master
